### ISSUE TITLE
Error "Found an abbreviation code that has already been used"

### ISSUE THREAD

**Issue by xtuc** [gimli-rs/gimli#668]
Hi,

When compiling from Rust to Wasm, the DWARF info are sometimes invalid to gimli and throw "Found an abbreviation code that has already been used". It seems to happen only with larger codebases and I don't have a good way to reproduce at the moment.

Is that a know issue by any chance? Please let me know what you need to debug.

**Comment by philipc** [comment]
Can you provide a file that this occurs for, or otherwise provide steps to reproduce the error? Do other tools work on the file, such as llvm-dwarfdump?

**Comment by xtuc** [comment]
llvm-dwarfdump crashes as well:
```

...
warning: mismatching address size at offset 0x00274d05 expected 0x04 found 0x4f
warning: address size 0x4f of DW_LNE_set_address opcode at offset 0x00274d05 is unsupported
warning: unexpected line op length at offset 0x002d8dc4 expected 0x03 found 0x02
warning: mismatching address size at offset 0x002dc17b expected 0x04 found 0x02
warning: unexpected line op length at offset 0x002ec1a9 expected 0x03 found 0x0a
warning: unexpected line op length at offset 0x00321947 expected 0x29 found 0x02
warning: mismatching address size at offset 0x00470ae0 expected 0x04 found 0x02
...

0x000002eb:         DW_TAG_structure_type
                      DW_AT_name        ("NonNull<u64>")
                      DW_AT_byte_size   (0x04)
                      DW_AT_alignment   (4)

0x000002f2:           DW_TAG_template_type_parameter
                        DW_AT_type      (0x0000053b "
Program received signal SIGSEGV, Segmentation fault.

(gdb) bt
#0  0x00007ffff3d19145 in llvm::DWARFAbbreviationDeclaration::getAttributeOffsetFromIndex(unsigned int, unsigned long, llvm::DWARFUnit const&) const () from /lib/x86_64-linux-gnu/libLLVM-14.so.1
#1  0x00007ffff3d1943f in llvm::DWARFAbbreviationDeclaration::getAttributeValue(unsigned long, llvm::dwarf::Attribute, llvm::DWARFUnit const&) const () from /lib/x86_64-linux-gnu/libLLVM-14.so.1
```

I'll try to send a repro.

**Comment by xtuc** [comment]
I can reproduce on another project that I can share. This time llvm-dwarfdump doesn't crash, it stops with:
```
0x002f1083: Compile Unit: length = 0x0000063c, format = DWARF32, version = 0x0004, abbr_offset = 0x31d6a, addr_size = 0x04 (next unit at 0x002f16c3)
warning: DWARF unit at offset 0x002f1083 contains invalid abbreviation 1 at offset 0x002f108f, valid abbreviations are 
<compile unit can't be parsed!>
```

See [debug-58a3a4f8-21c4-49da-936c-974edf11f21d.wasm.zip](https://github.com/gimli-rs/gimli/files/12194065/debug-58a3a4f8-21c4-49da-936c-974edf11f21d.wasm.zip)

**Comment by philipc** [comment]
Yes, I'll have a look later, but it sounds like this is a bug in the compiler producing the DWARF, and it is correct for gimli to give an error for this.

**Comment by xtuc** [comment]
Should I report the issue to Rust, since it seems to be emitting invalid DWARF?

**Comment by philipc** [comment]
Yes, this looks like a compiler bug or linker bug. The .debug_abbrev section is missing the final null code byte at the end of an abbreviation list for the first unit, so gimli continues parsing the abbreviations for the following unit and encounters a duplicate. Additionally, the abbreviation offset for the second unit is set as if there was an null code byte (the duplicate occurs at offset 0x27c, but the second unit specifies an abbrev_offset of 0x27d), so parsing abbreviations for the second unit fails due to an invalid DW_CHILDREN value.
